trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: './src/framework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './framework.sln'
    testRunTitle: 'Test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    includesymbols: true
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd705c2ae-5d82-4633-a7f6-27f96c8e342c'

