trigger:
- release

pool:
  vmImage: 'windows-latest'


steps:

- task: DotNetCoreCLI@2
  displayName: 'pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    includesymbols: false
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '950cdf21-3433-4803-911e-20e2a9f7c35c'