trigger:
- staging

pool:
  name: West Coast

variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'


steps:
- task: PowerShell@2
  displayName: 'Initilization'
  inputs:
    targetType: 'inline'
    script: |
      . $(Build.SourcesDirectory)/ci.ps1;
      Backup-DirectoryBuild;
      Set-ReleaseVersion -branch '$(Build.SourceBranchName)' -build $(Build.BuildId)
    pwsh: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: $(solution)
    feedsToUse: 'select'
    vstsFeed: 'Staging'
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    verbosityPack: Minimal
    packagesToPack: 'src/**/*.csproj'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Push Packages'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Staging'
    verbosityRestore: Minimal

