trigger:
- release

pool:
  vmImage: 'windows-latest'


steps:

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    projects: './framework.sln'
    testRunTitle: 'Test'

- task: DotNetCoreCLI@2
  displayName: 'pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    includesymbols: false
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  displayName: 'push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd705c2ae-5d82-4633-a7f6-27f96c8e342c'

