trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: './src/framework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './framework.sln'
    testRunTitle: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './framework.sln'
    testRunTitle: 'Test'