trigger:
- staging

pool:
  name: Default

resources:
  repositories:
  - repository: devops
    type: git
    name: devops\devops
    ref: refs/heads/staging


extends:
  template: api-build-template.yml@devops
  parameters:
    project: framework
    hasApp: false
    hasDocFx: true
    hasNuget: false

