git checkout staging
git merge authentication
git merge azure
git merge caching
git merge codegen
git merge collections
git merge config
git merge crypto
git merge dates
git merge efcore
git merge eventing
git merge excel
git merge hosting
git merge io
git merge logging
git merge math
git merge messaging
git merge reflection
git merge serialization
git merge text
git merge threading
git merge webclient