using System.CommandLine;
using System.CommandLine.Parsing;
using System.Threading.Tasks;

namespace Sample.CommandLine {
		internal class Program {
			static Task<int> Main(string[] args) =>
				new MySetup()
					// this method is generated by CodeGen
					.AddCommands()
					.CommandBuilder
					.Build()
					// If this call is used, the non async method of the command handler will be invoked
					//.Invoke(args)
					.InvokeAsync(args);
		}
}