// <auto-generated />
using System;
using Albatross.Repository.UnitTest.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Albatross.Repository.UnitTest.Migrations.CRMSqlServer
{
    [DbContext(typeof(CRMDbSqlMigrationSession))]
    [Migration("20191103222425_CRMDbSqlMigration_Create")]
    partial class CRMDbSqlMigration_Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Albatross.Repository.UnitTest.Model.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(100);

                    b.Property<int>("ContactID");

                    b.Property<DateTime>("Created");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("State")
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .HasMaxLength(100);

                    b.HasKey("AddressID");

                    b.HasIndex("ContactID");

                    b.ToTable("Address","test");
                });

            modelBuilder.Entity("Albatross.Repository.UnitTest.Model.Composite", b =>
                {
                    b.Property<string>("App");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("App", "Name");

                    b.ToTable("Composite","test");
                });

            modelBuilder.Entity("Albatross.Repository.UnitTest.Model.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Tag");

                    b.HasKey("ContactID");

                    b.HasAlternateKey("Name");

                    b.ToTable("Contact","test");
                });

            modelBuilder.Entity("Albatross.Repository.UnitTest.Model.Address", b =>
                {
                    b.HasOne("Albatross.Repository.UnitTest.Model.Contact", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
