using Sample.EFCore.Models;
using System.Collections.Generic;

namespace Albatross.DateLevel.Test {
	public static class Constant {
		public readonly static IEnumerable<Market> AllMarkets = new Market[]{
			new Market("EC"),
			new Market("LL"),
			new Market("ST"),
			new Market("IR"),
			new Market("CF"),
			new Market("NG"),
			new Market("CL"),
			new Market("CO"),
			new Market("HO"),
			new Market("TY"),
			new Market("C "),
			new Market("QS"),
			new Market("HG"),
			new Market("XB"),
			new Market("EO"),
			new Market("XP"),
			new Market("XM"),
			new Market("YM"),
			new Market("FV"),
			new Market("US"),
			new Market("TU"),
			new Market("VG"),
			new Market("GX"),
			new Market("RX"),
			new Market("OE"),
			new Market("DU"),
			new Market("UB"),
			new Market("HC"),
			new Market("HI"),
			new Market("TP"),
			new Market("KW"),
			new Market("ER"),
			new Market("Z "),
			new Market("G "),
			new Market("L "),
			new Market("SI"),
			new Market("CC"),
			new Market("KC"),
			new Market("SB"),
			new Market("CT"),
			new Market("GC"),
			new Market("NQ"),
			new Market("ES"),
			new Market("IH"),
			new Market("PT"),
			new Market("CN"),
			new Market("IB"),
			new Market("QC"),
			new Market("LA"),
			new Market("LP"),
			new Market("LN"),
			new Market("LX"),
			new Market("S "),
			new Market("BO"),
			new Market("W "),
			new Market("SM"),
			new Market("LC"),
			new Market("LH"),
			new Market("FC"),
			new Market("BJ"),
			new Market("NI"),
			new Market("PE"),
			new Market("JB"),
			new Market("CD"),
			new Market("BP"),
			new Market("AD"),
			new Market("ED"),
			new Market("SF"),
			new Market("RY"),
			new Market("JY"),
			new Market("NV"),
			new Market("DM"),
			new Market("DF"),
			new Market("UX"),
			new Market("DED"),
			new Market("MO"),
			new Market("IK"),
			new Market("MES"),
			new Market("OAT"),
			new Market("QZ"),
			new Market("RTY"),
			new Market("SFR"),
			new Market("SFI"),
		};
	}
}
